honeybadger-io/honeybadger-python

honeybadger/payload.py

`.message` is not defined for all exception classes. For example, `OSError` and `IOError` store error information in `errno`, `filename`, and `strerror`. `str()` is the most general method of converting objects to text, and for well-written exception classes it produces desired results. Compare
```
>>> ex.message
''
```
with
```
>>> str(ex)
'[Errno 2] No such file or directory'
```

Convert exception to error message using str()

---

CHANGELOG.md
honeybadger/config.py
honeybadger/core.py
honeybadger/fake_connection.py
honeybadger/tests/test_config.py
honeybadger/tests/test_core.py
honeybadger/tests/test_fake_connection.py
setup.py

The python library by default tries to hit the honeybadger server it doesn't matter in which environment you are on. If you don't want to, is really annoying because you don't provide a valid key for the library to connect but it creates unnecessary noise. The aim of this PR is to enhance the functionality of the library so when you are in a development like environment it doesn't hit the honeybadger server by default and the applications don't have to worry about that unless really necessary.
The core and general functionality of the library was kept the same, but just expanding for what it was mentioned before.
This PR was inspired in using the same functionality that is present in the ruby library. The behaviour is really similar and the implementation is based as well on the ruby …

Block call to honeybadger server when development like environment

---

honeybadger/core.py
honeybadger/tests/test_core.py

Added `_get_context` and `_get_request` methods to core Honeybadger object to return sane defaults from thread local data if the data hasn't been set yet (eg. after a thread has been forked)
Added an integration test to make sure `.notify` works properly within a new thread.
Fixes #20

Fix thread local issues

---

honeybadger/payload.py
honeybadger/tests/test_payload.py

I have a project that uses [lxml](http://lxml.de). This package is written in Cython (C native code). Our code parses a given XML document using XSD schema and then performs schematron validation. 
Any issue during the process results in raising an exception.
A stacktrace might include relative paths to source files. When a code, that had failed, comes from an external package that is built using a native code (for example with Cython), calling `open` will raise the "file not found" exception. As the result, sending a notification will fail on creating payload and the exception won't be reported (except the local logs if configured).
For example, this stackgrace, that comes from parsing an invalid XML document, includes references to relative paths:
```
Python 3.6.4 (default, Jan  6 2018, …
```

Don't fail when source file is missing

---

.travis.yml
honeybadger/contrib/flask.py
honeybadger/tests/contrib/test_flask.py
scripts/install_frameworks.sh
setup.py

This PR adds tests for all the currently supported framework versions (Django 1.11.x LTS, 2.1.x and 2.2.x, Flask 1.0 and 1.1) and their supported Python versions (2.7, 3.4, 3.5, 3.6, 3.7)
We've dropped support for any framework or Python versions not listed here.

Run tests on all currently supported framework versions and their supported Python versions

---

honeybadger/core.py

Bug fix for `with honeybadger.context` when using threads (Flask, gevent)
The change resolves issues where the context attribute is not initialized in the current thread which results in:
```
File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
return next(self.gen)
File "/Users/me/Envs/workforce_optimizer-rqDNrIoM/lib/python3.7/site-packages/honeybadger/core.py", line 67, in context
self.thread_local.context.update(kwargs)
File "src/gevent/local.py", line 408, in gevent._local.local.__getattribute__
AttributeError: 'gevent._local.local' object has no attribute 'context'
```

Fix context for threads

---

.travis.yml
.vscode/settings.json
README.md
honeybadger/tests/contrib/test_django.py
honeybadger/tests/contrib/test_flask.py
run_tests.sh
setup.py
test.sh

This PR retires Python 2 by removing all references to it and removing it from the Travis test matrix.
I've also updated the README to reflect the latest tested versions, as well as the Django documentation.
Fixes #45 .

Retire Python 2

---

honeybadger/payload.py
honeybadger/tests/test_payload.py

Instead of sending the snippet for just the first line (deprecated in our API), this adds a snippet for each line of the backtrace.

Add source snippets to backtrace lines

---

.github/workflows/python.yml
scripts/install_frameworks.sh
setup.py

Added an environment export to the install dependencies step, and added a version constraint to the MarkupSafe dependency so that all tests pass on Github Actions.

get GH actions tests passing

---

.github/workflows/python.yml
honeybadger/payload.py

Fixes #36 - swaps out the builtin `os.getloadavg()` for `psutil.getloadavg()` which is supported on both Windows and Linux.

Fixes load avg bug on Windows

---

honeybadger/payload.py
honeybadger/tests/test_payload.py

It's difficult or impossible to install psutil in an AWS Glue environment. This PR makes it so psutil is still a dependency, but those of us using it in a serverless environment that doesn't work well with psutil can explicitly exclude it, while still using honeybadger-python.
Fixes #62
Example of an error reported from AWS Glue:

Make psutil optional for use in serverless environments

---

honeybadger/contrib/django.py

Django's request parameters is always found in request.GET for get requests and request.POST for PATCH & PUT requests.
attributes for other request method does not exist in the request object.

fixed wrong getattr statement

---

CHANGELOG.md
honeybadger/config.py
honeybadger/contrib/django.py
honeybadger/contrib/flask.py
honeybadger/tests/contrib/test_flask.py

- Added 'CSRF_COOKIE' to default filter_params
- Added filtering to meta attributes for flask or & django
- Added filtered cookies to cgi_data for flask & django
- removed conversion of request.META to dict because it is a dict by default
Fixes #43 
Fixes #44

filter sensitive headers & cookies

---

README.md
honeybadger/contrib/__init__.py
honeybadger/tests/contrib/test_fastapi.py

Hello,
I just noticed that with #84 I introduced a dependency issue with fastapi preventing the correct initialization of Honeybadger.
This was caused by the `auto_discover_plugins` functionality importing the `contrib` package, and therefore raising an error when `fastapi` is not installed in your environment.
This pull request fixes that issue, and requires explicitly importing the `HoneybadgerRoute` for the "advanced" `apiRoute` usage in FastAPI.
(The tests completed successfully because `fastapi` is a dependency in the test environment).
What do you think? Does this makes sense to you, @Kelvin4664 ?
Thank you!

fix: fastapi dependency issue.

---

README.md

Since we ignore errors in development environment, the example shouldn't use that as the configured environment. ;)

Fix the Flask info

---

CHANGELOG.md
honeybadger/payload.py
honeybadger/tests/test_payload.py

Fixes #115
Allow passing fingerprint in `notify()` through the `context` parameter.

feat: allow passing fingerprint in notify

---

CHANGELOG.md
README.md
honeybadger/payload.py
honeybadger/tests/test_payload.py

- Makes `fingerprint` a top-level function parameter 
- Adds example using `fingerprint`

fix: make fingerprint a top-level parameter

---

README.md
honeybadger/config.py
honeybadger/payload.py
honeybadger/tests/test_payload.py

#122
Adds local_variables to request

Add local variables to notifications

---

setup.py

Per this [issue](https://github.com/tiangolo/fastapi/issues/5656), we need to add the httpx dependency with the latest version of fastapi.

chore: add httpx dep to fix ci

---

honeybadger/contrib/django.py
honeybadger/tests/contrib/django_test_app/middleware.py
honeybadger/tests/contrib/test_django.py

Honeybadger crashes when it tries to notify inside a custom Django middleware as the `request.resolver_match` is `None`.

Fix django with custom middlewares

---

.gitignore
CHANGELOG.md
README.md
honeybadger/contrib/aws_lambda.py

Closes: #159
Manually tested with python runtimes up to `3.12`.

feat(aws-lambda): add support for python 3.9+

---

README.md

There could be some confusion for some who are trying out the FastAPI examples. This PR seprates the two ways you can modify the router so that each example stands on its own.

Cleanup the FastAPI examples

---

honeybadger/utils.py

Remove deepcopy

---

CHANGELOG.md
examples/django_app/honeybadger_example/settings.py
honeybadger/contrib/django.py

Moves the `__set_user_from_context` method inside `process_exception` of the middleware definition.
More context on the fix:
- We [recommend](https://docs.honeybadger.io/lib/python/#django) to put Honeybadger's middleware at the top of the middleware list.
- When this middleware is executed, `request.user` is not set yet from the other middleware. The current approach was trying to set the user session before passing on to the other middleware.
- The solution is to move the method which sets the user into Honeybadger's context closer to the exception (`process_exception`). At that point, it is more probable to have the user session available if the proper middleware have been executed (i.e. `django.contrib.auth.middleware.AuthenticationMiddleware`).
Fixes: #155

fix(django): capture user name and id

---

README.md

Hi there :wave: 
```
>>> try:
...     int("asd")
... except ValueError, e:
File "<stdin>", line 3
except ValueError, e:
^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
```
Another thing: Since `exception` is really a keyword argument, perhaps the documented way to call `notify()` should be `notify(exception=exc, ...)` ?

Syntax error in docs

---

honeybadger/config.py
honeybadger/connection.py
honeybadger/core.py
honeybadger/fake_connection.py
honeybadger/notice.py
honeybadger/tests/contrib/test_celery.py
honeybadger/tests/test_config.py
honeybadger/tests/test_connection.py
honeybadger/tests/test_core.py
honeybadger/tests/test_fake_connection.py
honeybadger/tests/test_notice.py

The main goal of this PR was to add a `before_notify` hook as part of the configuration. This allows the library to be configured to intercept, inspect, and alter a error notice before it is sent off to Honeybadger.
To make this easier, a new `Notice` class has been added so that there is a single object that gets passed into the hook. ~~The payload is generate upon instantiation and can be later inspected or altered in the hook.~~
~~This preemptive generation isn't ideal because it's a little cumbersome to work with the notice payload. However, the plugins implement the `generate_payload` method which takes in the formatted notice payload. After this, I'd like to take a stab at making it easier to manipulate a notice without having to dig into the final payload.~~
The payload is a cached …

feat: add a notice class and before_notify hook

---

CHANGELOG.md

I didn't realize that we should be building up items in the Unreleased section of the changelog. These get used as part of the release script.

fix: update changelog for upcoming 0.23.0 release

---

CHANGELOG.md
honeybadger/notice.py
honeybadger/tests/test_notice.py

This removes the exception raised in the Notice class and fixes the logic for assigning the hash to the exception attribute when an an exception is not present.
Also took the liberty to cleanup the initialization of the class to be a bit clearer.

feat: no longer raise exception in notice class

---

README.md
honeybadger/config.py
honeybadger/contrib/asgi.py
honeybadger/contrib/celery.py
honeybadger/contrib/django.py
honeybadger/contrib/flask.py
honeybadger/tests/contrib/test_asgi.py
honeybadger/tests/contrib/test_celery.py
honeybadger/tests/contrib/test_django.py
honeybadger/tests/contrib/test_flask.py
honeybadger/utils.py

This includes the basic framework hooks & tests for Django, Flask, ASGI & Celery. 
A few notes:
- I'm still not sure why, but the way I changed the Celery app made the previous testing strategy non-functional. Because of this I reworked the tests to use pytest and a bit more mocking. If anyone knows how to write a unit test that actually runs a Celery task **with events** (without loading docker containers), please let me know :)
- I patched each database implementation individually for Django and Flask within the middleware. I created a generic DB shim, but I could not get it to load in the right order, so I did not include it with this PR. If I have time after all the other tasks I might take another stab at getting it to work for apps that are not Django and Flask.
- I had included …

feat(insights): basic framework event hooks

---

CHANGELOG.md
honeybadger/fake_connection.py

This updates the fake_connection to return the same type result as the connection, which will fix issues with the events_worker expecting the correct type in dev.

fix(insights): fix result in fake_connection

---

dev-requirements.txt
honeybadger/connection.py
honeybadger/context_store.py
honeybadger/core.py
honeybadger/notice.py
honeybadger/protocols.py
honeybadger/tests/contrib/test_asgi.py
honeybadger/tests/test_core.py
honeybadger/tests/test_notice.py
honeybadger/types.py
pytest.ini

This adds a new set of functions to the `Honeybadger` class for setting and applying event context.
I also refactored the internals of storing context quite a bit:
* Replaced the threadlocals with a `ContextStore` class that uses `ContextVar`, which is the recommended way to manage thread local variables in a 3.7+ world.
* Used `ContextStore` to create both notice and event context stores
* Updated the core methods to delegate to the new instances
* I refactored the Notice class by removing the thread local code, opting to just send in the context & tag variable, keeping it just a pure rendering class.

feat(insights): event_context

---

CHANGELOG.md
honeybadger/notice.py
honeybadger/tests/test_core.py

Partially fixes #221
This reverts back to the previous way we dealt with a missing exception.

fix: create dict for missing exception

---

honeybadger/__init__.py

@joshuap reported that Python throws an error when trying to register the signal handler in any other thread than the main:
```
File "/Users/josh/tmp/django-monitoring/django-monitoring/.venv/lib/python3.12/site-packages/honeybadger/__init__.py", line 30, in <module>
signal.signal(signal.SIGTERM, _on_term)
File "/Users/josh/.local/share/uv/python/cpython-3.12.11-macos-aarch64-none/lib/python3.12/signal.py", line 58, in signal
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: signal only works in main thread of the main interpreter
```
Usually, Honeybadger's initialization code runs on the main thread, but it is possible for it to run in another thread, such as when running django in dev mode …

fix: register signal handler only in main thread

---

.github/workflows/code-quality.yml
.github/workflows/python.yml

This change will cancel in-progress CI workflows if new code is pushed. This helps saves Github CI minutes usage and CI run time, since you don't have to wait for previous, outdated workflows to complete.

chore: add concurrency control to GitHub workflows

---

honeybadger/events_worker.py

A lock-free implementation of the `EventsWorker.push()`.
Note that the PR targets the insights-instrumentation branch.

perf: lock-free events_worker.push
