honeybadger-io/honeybadger-python

- honeybadger/utils.py
> Remove has_key to ensure python3 compatibility

- honeybadger/tests/contrib/test_flask.py
Fix failing flask test by using `kwargs` with `test_request_context`.
> Fix failing flask test

- honeybadger/payload.py
- honeybadger/tests/test_payload.py
This PR updates the snippet offsets to behave as expected, as described in #51. Also updates the tests accordingly.
> Updated snippet offsets + tests to behave per requirement

- .github/workflows/python.yml
- honeybadger/tests/test_utils.py
- honeybadger/utils.py
- scripts/install_frameworks.sh
- setup.py
Updated the `filter_dict` function to add a recursive check for nested keys that should be filtered + supporting test.
Fixes #57
> Add support for filtering nested params

- README.md
> updated readme for aws lambda

- honeybadger/contrib/aws_lambda.py
- honeybadger/contrib/django.py
- honeybadger/contrib/flask.py
- honeybadger/plugins.py
- honeybadger/tests/contrib/test_django.py
- honeybadger/tests/contrib/test_flask.py
- honeybadger/tests/test_plugins.py
#77 
- Combine payload generated byall registered plugins
- updated a few corresponding test cases
#79 
-Catch attribute error when initialising handler for latest lambda runtime
> Merge plugins

- .github/workflows/python.yml
- CHANGELOG.md
- README.md
- examples/fastapi/app.py
- examples/fastapi/custom_route.py
- honeybadger/contrib/__init__.py
- honeybadger/contrib/asgi.py
- honeybadger/contrib/fastapi.py
- honeybadger/plugins.py
- honeybadger/tests/contrib/test_asgi.py
- honeybadger/tests/contrib/test_fastapi.py
- setup.py
Hello! I'm proposing the following PR that should close #78.
This PR adds ASGI applications support and a custom FastAPI route.
I added some tests and update the documentation.
What do you think @joshuap and @Kelvin4664?
> ASGI middleware/plugin.

- README.md
> document force_sync

- README.md
- honeybadger/tests/test_core.py
Adds test cases to #98 in order to get it merged.
@joshuap let me know if anything else here needs to be done, the way I tested for the exclusion is not ideal but I had no better idea within this testing setup :)
> Add test case for excluded exceptions

- .github/workflows/pypi-publish.yml
- README.md
> Github Actions workflow to publish on PyPi

- honeybadger/core.py
- honeybadger/payload.py
- honeybadger/tests/test_core.py
> feat: add fingerprint in notify

- honeybadger/contrib/celery.py
> import celery only when needed

- README.md
> docs: add note for django debug

- honeybadger/core.py
- honeybadger/tests/test_core.py
I'd like to be able to pass in a dict of context, in addition to using keyword arguments.
Thanks!
> Set context with dict arg or kwargs

- examples/django_app/app/urls.py
- examples/django_app/honeybadger_example/settings.py
- examples/django_app/honeybadger_example/urls.py
- examples/django_app/requirements.txt
- fix deprecated django.conf.urls.url()
- bump to Django 4.2LTS
> Make Django example actually generate an alert

- .github/workflows/python.yml
- CHANGELOG.md
- also update 2.2 & 3.2 LTS revs
- update actions to use Node.js 16
- update changelog with this and last PR merged
> target Django 4.2LTS in CI but not with Python v3.7

- CHANGELOG.md
- honeybadger/tests/contrib/test_django.py
> Update version matrix to run tests in newer versions of django

- honeybadger/tests/contrib/test_asgi.py
> Add missing await in test

- honeybadger/contrib/django.py
> feat: capture username in django

- honeybadger/contrib/django.py
https://github.com/honeybadger-io/honeybadger-python/pull/155#issuecomment-1638532143
> feat: add user id to context

- .github/workflows/python.yml
- honeybadger/contrib/flask.py
> feat: add support for flask v3

- CHANGELOG.md
- README.md
> Add documentation for honeybadger.event
